# Generated by Django 3.2.25 on 2026-02-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='attended_by',
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Direct', 'Direct Contact'), ('Website', 'Website'), ('Manual', 'Manual Entry'), ('Referral', 'Referral')], default='Manual', max_length=50),
        ),
    ]
