# Generated by Django 3.2.25 on 2026-02-24 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('package', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Converted', 'Converted'), ('Junk', 'Junk')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(choices=[('Direct', 'Direct Contact'), ('Website', 'Website'), ('Manual', 'Manual Entry'), ('Referral', 'Referral')], default='Manual', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='travel_packages/')),
                ('active', models.BooleanField(default=True)),
                ('itinerary', models.TextField(blank=True, null=True)),
                ('inclusions', models.TextField(blank=True, null=True)),
                ('exclusions', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('hotel', 'Luxury Hotel'), ('resort', 'Mountain Resort'), ('beach', 'Beach Resort'), ('villa', 'Villa'), ('apartment', 'Apartment')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField()),
                ('summary', models.TextField()),
                ('owner_name', models.CharField(blank=True, max_length=150, null=True)),
                ('owner_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amenities', models.ManyToManyField(blank=True, to='admin_panel.Amenity')),
            ],
        ),
    ]
