# Generated by Django 3.2.25 on 2026-02-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_amenity_inquiry_lead_property_travelpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='draft', max_length=20)),
                ('package_id', models.CharField(blank=True, max_length=50, null=True)),
                ('author_name', models.CharField(max_length=100)),
                ('author_summary', models.TextField(max_length=500)),
                ('reading_time', models.PositiveIntegerField(default=1)),
                ('publish_date', models.DateField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/featured/')),
                ('featured_image_url', models.URLField(blank=True, null=True)),
                ('hashtags', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
