# Generated by Django 3.2.25 on 2026-02-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='story_main_image',
            field=models.ImageField(blank=True, null=True, upload_to='package_stories/'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='story_side_image1',
            field=models.ImageField(blank=True, null=True, upload_to='package_stories/'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='story_side_image2',
            field=models.ImageField(blank=True, null=True, upload_to='package_stories/'),
        ),
    ]
