# Generated by Django 3.2.25 on 2026-02-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='property',
            name='owner_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('hotel', 'Luxury Hotel'), ('resort', 'Mountain Resort'), ('beach', 'Beach Resort'), ('villa', 'Villa'), ('apartment', 'Apartment')], max_length=50),
        ),
    ]
