# Generated by Django 3.2.25 on 2026-02-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20260227_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags', max_length=255, null=True),
        ),
    ]
