# Generated by Django 3.2.25 on 2026-02-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20260224_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
