# Generated by Django 3.2.25 on 2026-02-27 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20260227_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='admin_panel.lead'),
        ),
    ]
