# Generated by Django 6.0.2 on 2026-02-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_rename_date_of_birth_employee_join_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='meal_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='price',
        ),
        migrations.AddField(
            model_name='meal',
            name='included_meals',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='employee/'),
        ),
    ]
