# Generated by Django 3.2.25 on 2026-02-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_blog_tags'),
        ('admin_panel', '0005_inquiry_lead'),
    ]

    operations = [
    ]
