# Generated by Django 3.2.25 on 2026-02-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_merge_0005_blog_tags_0005_inquiry_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='enquiry_type',
            field=models.CharField(choices=[('General', 'General Enquiry'), ('International', 'International'), ('Domestic', 'Domestic')], default='General', max_length=50),
        ),
    ]
