# Generated by Django 6.0.2 on 2026-02-24 08:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_rename_invoice_number_invoice_invoice_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='voucher_code',
            new_name='voucher_no',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='description',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='status',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='valid_till',
        ),
        migrations.AddField(
            model_name='voucher',
            name='adults',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.account'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='checkin_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='voucher',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='checkout_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='voucher',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.customer'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='from_whytehouse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='meals_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.meal'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='nights',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voucher',
            name='no_of_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voucher',
            name='note_for_guest',
            field=models.TextField(blank=True, default='', max_length=130),
        ),
        migrations.AddField(
            model_name='voucher',
            name='note_for_resort',
            field=models.TextField(blank=True, default='', max_length=130),
        ),
        migrations.AddField(
            model_name='voucher',
            name='package_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='pax_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='voucher',
            name='pending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='resort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.resort'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='resort_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='room_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='voucher',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.employee'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='voucher_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
