# Generated by Django 3.2.25 on 2026-02-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_lead_enquiry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Direct', 'Direct Contact'), ('Website', 'Website'), ('Manual', 'Manual Entry'), ('Referral', 'Referral'), ('Enquire Now', 'Enquire Now')], default='Manual', max_length=50),
        ),
    ]
