# Generated by Django 3.2.25 on 2026-02-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_auto_20260227_1604'),
        ('admin_panel', '0009_auto_20260228_0906'),
    ]

    operations = [
    ]
