# Generated by Django 3.2.25 on 2026-02-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], default='Domestic', max_length=20),
        ),
    ]
