# Generated by Django 3.2.25 on 2026-02-27 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_destination_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.destination'),
        ),
    ]
