# Generated by Django 3.2.25 on 2026-03-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('destinations', 'Destinations'), ('travel_tips', 'Travel Tips'), ('food_culture', 'Food & Culture'), ('packages', 'Packages & Deals'), ('honeymoon', 'Honeymoon'), ('family_travel', 'Family Travel'), ('adventure', 'Adventure'), ('travel_stories', 'Travel Stories'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
