# Generated by Django 3.2.25 on 2026-03-02 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_lead_status'),
        ('admin_panel', '0016_alter_blog_status'),
    ]

    operations = [
    ]
