# Generated by Django 3.2.25 on 2026-03-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_merge_0014_lead_status_0016_alter_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
