# Generated by Django 3.2.25 on 2026-03-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
