# Generated by Django 3.2.25 on 2026-03-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_auto_20260304_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('Travel Package', 'Travel Package'), ('Customer Service', 'Customer Service'), ('Booking Experience', 'Booking Experience'), ('Transportation', 'Transportation'), ('Hotel / Resort', 'Hotel / Resort'), ('Food / Meals', 'Food / Meals'), ('Tour Guide', 'Tour Guide'), ('Website Experience', 'Website Experience'), ('Trip Management', 'Trip Management'), ('Overall Experience', 'Overall Experience'), ('Other', 'Other')], default='Overall Experience', max_length=50),
        ),
    ]
