# Generated by Django 3.2.25 on 2026-03-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_feedbackimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('Travel Package', 'Travel Package'), ('Customer Service', 'Customer Service'), ('Booking Experience', 'Booking Experience'), ('property management', 'property management'), ('Website Experience', 'Website Experience'), ('Trip Management', 'Trip Management'), ('Other', 'Other')], default='Overall Experience', max_length=50),
        ),
    ]
