# Generated by Django 3.2.25 on 2026-03-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_alter_feedback_feedback_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('Travel Package', 'Travel Package'), ('Customer Service', 'Customer Service'), ('Booking Experience', 'Booking Experience'), ('Property Management', 'Property Management'), ('Website Experience', 'Website Experience'), ('Trip Management', 'Trip Management'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
