# Generated by Django 3.2.25 on 2026-03-09 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0028_alter_feedback_feedback_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('travel', 'Travel'), ('adventure', 'Adventure'), ('culture', 'Culture'), ('food', 'Food'), ('tips', 'Tips')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admin_panel.blog'),
        ),
    ]
