# Generated by Django 3.2.25 on 2026-03-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0029_auto_20260309_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/maps/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='packages_start_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
