# Generated by Django 3.2.25 on 2026-03-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_add_property_is_active'),
        ('admin_panel', '0030_auto_20260311_1113'),
    ]

    operations = [
    ]
