# Generated by Django 3.2.25 on 2026-03-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_merge_20260311_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='admin_panel.employee'),
        ),
    ]
