# Generated by Django 3.2.25 on 2026-03-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_lead_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='package_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
