# Generated by Django 3.2.25 on 2026-03-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0035_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='enquiry_type',
            field=models.CharField(choices=[('General', 'General Enquiry'), ('International', 'International'), ('Domestic', 'Domestic'), ('Hospitality', 'Hospitality')], default='General', max_length=50),
        ),
    ]
