# Generated by Django 3.2.25 on 2026-03-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0035_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
