# Generated by Django 3.2.25 on 2026-03-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0036_alter_lead_enquiry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='property_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
