# Generated by Django 3.2.25 on 2026-03-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0037_lead_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='package_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
