# Generated by Django 3.2.25 on 2026-03-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0036_auto_20260312_1209'),
        ('admin_panel', '0038_lead_package_name'),
    ]

    operations = [
    ]
