# Generated by Django 3.2.25 on 2026-03-19 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0039_merge_0036_auto_20260312_1209_0038_lead_package_name'),
    ]

    operations = [
        migrations.RunSQL("UPDATE admin_panel_blog SET category = NULL"),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='admin_panel.blogcategory'),
        ),
    ]
