# Generated by Django 3.2.25 on 2026-03-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0040_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
