# Generated by Django 3.2.25 on 2026-03-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0045_destination_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='alternate_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
