# Generated by Django 3.2.25 on 2026-03-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0046_lead_alternate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='price_type',
            field=models.CharField(blank=True, default='Per Package', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
