# Generated by Django 3.2.25 on 2026-03-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0046_lead_alternate_number'),
    ]

    operations = [
        # Rename existing fields
        migrations.RenameField(
            model_name='resort',
            old_name='location',
            new_name='resort_place',
        ),
        migrations.RenameField(
            model_name='resort',
            old_name='contact_person',
            new_name='owner_manager_name',
        ),
        migrations.RenameField(
            model_name='resort',
            old_name='contact_number',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='resort',
            old_name='address',
            new_name='full_address',
        ),
        # Add new fields
        migrations.AddField(
            model_name='resort',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='location_map_link',
            field=models.URLField(blank=True, help_text='Google Map Link', null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='cc_emails',
            field=models.TextField(blank=True, help_text='Comma-separated CC email addresses', null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='resorts/certificates/'),
        ),
        migrations.AddField(
            model_name='resort',
            name='id_proof',
            field=models.FileField(blank=True, help_text='Aadhaar/PAN Upload', null=True, upload_to='resorts/id_proofs/'),
        ),
        migrations.AddField(
            model_name='resort',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='number_of_rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated amenities', null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='resort_images',
            field=models.FileField(blank=True, help_text='Multiple images can be uploaded separately', null=True, upload_to='resorts/images/'),
        ),
        migrations.AddField(
            model_name='resort',
            name='resort_video',
            field=models.FileField(blank=True, null=True, upload_to='resorts/videos/'),
        ),
        migrations.AddField(
            model_name='resort',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='social_media_links',
            field=models.TextField(blank=True, help_text='Comma-separated social media links', null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='google_listing_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
