# Generated by Django 3.2.25 on 2026-03-31 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0048_meal_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResortRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_name', models.CharField(max_length=150)),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('price_per_night', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_guests', models.PositiveIntegerField(default=1)),
                ('room_size', models.CharField(blank=True, max_length=100, null=True)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated amenity values (AC, WiFi, Balcony, etc.)', null=True)),
                ('room_images', models.FileField(blank=True, null=True, upload_to='resorts/room_types/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='meal',
            name='price_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per person in INR', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='resort',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='resort',
            name='owner_manager_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ResortRoomTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resorts/room_type_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type_images', to='admin_panel.resortroomtype')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='resortroomtype',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='admin_panel.resort'),
        ),
        migrations.CreateModel(
            name='ResortImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resorts/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_images_list', to='admin_panel.resort')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
