# Generated by Django 3.2.25 on 2026-03-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0049_auto_20260331_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
