# Generated by Django 3.2.25 on 2026-03-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0047_auto_20260331_1420'),
        ('admin_panel', '0050_remove_voucher'),
    ]

    operations = [
    ]
