# Generated by Django 3.2.25 on 2026-04-01 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0051_merge_0047_auto_20260331_1420_0050_remove_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('voucher_date', models.DateField(blank=True, null=True)),
                ('checkin_date', models.DateField(blank=True, null=True)),
                ('checkout_date', models.DateField(blank=True, null=True)),
                ('checkin_time', models.TimeField(blank=True, null=True)),
                ('checkout_time', models.TimeField(blank=True, null=True)),
                ('adults', models.IntegerField(default=0)),
                ('children', models.IntegerField(default=0)),
                ('pax_total', models.IntegerField(default=0)),
                ('pax_notes', models.TextField(blank=True, null=True)),
                ('nights', models.IntegerField(default=1)),
                ('room_type', models.CharField(blank=True, max_length=100)),
                ('no_of_rooms', models.IntegerField(default=1)),
                ('package_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('resort_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pending', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('from_whytehouse', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note_for_resort', models.TextField(blank=True, null=True)),
                ('note_for_guest', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.customer')),
                ('meals_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.meal')),
                ('resort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.resort')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.employee')),
            ],
            options={
                'ordering': ['-voucher_date', '-id'],
            },
        ),
    ]
