# Generated by Django 3.2.25 on 2026-04-01 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0052_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTransportOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_options', to='admin_panel.travelpackage')),
            ],
            options={
                'ordering': ['price_per_person'],
            },
        ),
        migrations.CreateModel(
            name='PackageRoomOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price_per_night', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_guests', models.PositiveIntegerField(default=2)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_options', to='admin_panel.travelpackage')),
            ],
            options={
                'ordering': ['price_per_night'],
            },
        ),
        migrations.CreateModel(
            name='PackageMealOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_options', to='admin_panel.travelpackage')),
            ],
            options={
                'ordering': ['price_per_person'],
            },
        ),
    ]
