# Generated by Django 3.2.25 on 2026-04-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0052_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='children_pricing',
            field=models.TextField(blank=True, default='[]', help_text="JSON list of age ranges with prices: [{'min_age': 0, 'max_age': 5, 'price': 0}, {'min_age': 6, 'max_age': 12, 'price': 250}]", null=True),
        ),
    ]
