# Generated by Django 3.2.25 on 2026-04-01 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0053_add_package_pricing_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageroomoption',
            name='package',
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='meal_plans',
            field=models.ManyToManyField(blank=True, related_name='packages', to='admin_panel.Meal'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='resort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='admin_panel.resort'),
        ),
        migrations.DeleteModel(
            name='PackageMealOption',
        ),
        migrations.DeleteModel(
            name='PackageRoomOption',
        ),
    ]
