# Generated by Django 3.2.25 on 2026-04-01 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0053_meal_children_pricing'),
        ('admin_panel', '0054_package_resort_meal_transport'),
    ]

    operations = [
    ]
