# Generated by Django 3.2.25 on 2026-04-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0055_merge_20260401_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='adult_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='child_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='price_type',
            field=models.CharField(blank=True, default='Per Person', max_length=20, null=True),
        ),
    ]
