# Generated by Django 3.2.25 on 2026-04-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0055_merge_20260401_1102'),
        ('admin_panel', '0055_merge_20260401_1104'),
    ]

    operations = [
    ]
