# Generated by Django 3.2.25 on 2026-04-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0056_merge_20260401_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='id_proof',
            field=models.FileField(blank=True, help_text='Aadhaar/PAN Upload', null=True, upload_to='resort/id_proofs/'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='resort/certificates/'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='resort_images',
            field=models.FileField(blank=True, help_text='Multiple images can be uploaded separately', null=True, upload_to='resort/images/'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='resort_video',
            field=models.FileField(blank=True, null=True, upload_to='resort/videos/'),
        ),
        migrations.AlterField(
            model_name='resortimage',
            name='image',
            field=models.ImageField(upload_to='resort/images/'),
        ),
        migrations.AlterField(
            model_name='resortroomtype',
            name='room_images',
            field=models.FileField(blank=True, null=True, upload_to='resort/room_types/'),
        ),
        migrations.AlterField(
            model_name='resortroomtypeimage',
            name='image',
            field=models.ImageField(upload_to='resort/room_type_images/'),
        ),
    ]
