# Generated by Django 3.2.25 on 2026-04-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0056_add_adult_child_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='child_pricing',
            field=models.TextField(blank=True, default='[]', help_text='JSON age brackets: [{min_age, max_age, price}]', null=True),
        ),
    ]
