# Generated by Django 3.2.25 on 2026-04-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0057_add_package_child_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetransportoption',
            name='max_persons',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of persons this transport can accommodate'),
        ),
    ]
