# Generated by Django 3.2.25 on 2026-04-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0056_merge_20260401_1106'),
        ('admin_panel', '0058_transport_max_persons'),
    ]

    operations = [
    ]
