# Generated by Django 3.2.25 on 2026-04-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0057_auto_20260401_1216'),
        ('admin_panel', '0059_merge_20260401_1219'),
    ]

    operations = [
    ]
