# Generated by Django 3.2.25 on 2026-04-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0060_merge_20260401_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetransportoption',
            name='min_persons',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='packagetransportoption',
            name='max_persons',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_bookings', to='admin_panel.customer')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='admin_panel.travelpackage')),
            ],
        ),
    ]
