# Generated by Django 3.2.25 on 2026-04-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0059_merge_20260401_1348'),
        ('admin_panel', '0061_add_transport_min_persons'),
    ]

    operations = [
    ]
