# Generated by Django 3.2.25 on 2026-04-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0062_merge_20260401_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='resort_name',
            field=models.CharField(max_length=255),
        ),
    ]
