# Generated by Django 3.2.25 on 2026-04-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0062_merge_20260401_1434'),
        ('admin_panel', '0063_remove_resort_name_unique'),
    ]

    operations = [
    ]
