# Generated by Django 3.2.25 on 2026-04-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0065_remove_package_unused_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='business_registration_number',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='city',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='google_listing_link',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='number_of_rooms',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='owner_manager_name',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='registration_certificate',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='resort_images',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='resort_video',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='social_media_links',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='state',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='website_url',
        ),
    ]
