# Generated by Django 3.2.25 on 2026-04-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0066_auto_20260403_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='children_pricing',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='price_per_person',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='status',
        ),
        migrations.AlterField(
            model_name='meal',
            name='included_meals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
