# Generated by Django 3.2.25 on 2026-04-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0067_auto_20260403_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeRole',
        ),
        migrations.RemoveField(
            model_name='resortimage',
            name='resort',
        ),
        migrations.RemoveField(
            model_name='resortroomtype',
            name='resort',
        ),
        migrations.RemoveField(
            model_name='resortroomtypeimage',
            name='room_type',
        ),
        migrations.DeleteModel(
            name='PackageTransportOption',
        ),
        migrations.DeleteModel(
            name='ResortImage',
        ),
        migrations.DeleteModel(
            name='ResortRoomType',
        ),
        migrations.DeleteModel(
            name='ResortRoomTypeImage',
        ),
    ]
